/* Neon Draw — built-in brush presets, grouped by category. */
'use strict';
(function () {
  const P = (name, cat, settings) => ({ name, cat, builtin: true, settings });

  const LIST = [
    /* Sketch */
    P('Pencil', 'Sketch', { engine: 'pixel', size: 4, softness: 0.05, flow: 0.7, pressureOpacity: true, stabilizer: 0.2 }),
    P('HB Pencil', 'Sketch', { engine: 'pixel', size: 5, softness: 0.2, flow: 0.85, tip: 'pencil', texture: 'paper', textureStrength: 0.55, pressureOpacity: true, pressureSize: true, minSize: 0.5, spacing: 0.08, stabilizer: 0.15 }),
    P('6B Pencil', 'Sketch', { engine: 'pixel', size: 9, softness: 0.3, flow: 0.9, tip: 'pencil', texture: 'paper', textureStrength: 0.75, pressureOpacity: true, minSize: 0.45, spacing: 0.07, stabilizer: 0.15 }),
    P('Coloured Pencil', 'Sketch', { engine: 'pixel', size: 8, softness: 0.25, flow: 0.8, tip: 'pencil', texture: 'rough', textureStrength: 0.7, pressureOpacity: true, minSize: 0.6, spacing: 0.08 }),
    P('Sketchy', 'Sketch', { engine: 'sketchy', variant: 'sketchy', size: 30, flow: 0.55, density: 30, stabilizer: 0, pressureSize: false }),
    P('Shaded Web', 'Sketch', { engine: 'sketchy', variant: 'shaded', size: 40, flow: 0.8, density: 40, stabilizer: 0, pressureSize: false }),
    P('Web', 'Sketch', { engine: 'sketchy', variant: 'web', size: 36, flow: 0.7, density: 34, stabilizer: 0, pressureSize: false }),
    P('Fur Lines', 'Sketch', { engine: 'sketchy', variant: 'fur', size: 30, flow: 0.9, density: 30, stabilizer: 0, pressureSize: false }),
    P('Hatching', 'Sketch', { engine: 'hatch', size: 22, flow: 0.7, spacing: 0.22, hatchAngle: 45, lineWidth: 1.2, pressureSize: true, stabilizer: 0.2 }),
    P('Cross Hatching', 'Sketch', { engine: 'hatch', size: 26, flow: 0.6, spacing: 0.2, hatchAngle: 45, cross: true, lineWidth: 1, pressureSize: true }),
    /* Ink */
    P('Ink Pen', 'Ink', { engine: 'pixel', size: 6, softness: 0, flow: 1, pressureSize: true, pressureOpacity: false, stabilizer: 0.45 }),
    P('Fine Liner', 'Ink', { engine: 'pixel', size: 2.5, softness: 0, flow: 1, pressureSize: false, stabilizer: 0.5, spacing: 0.08 }),
    P('G-Pen', 'Ink', { engine: 'pixel', size: 10, softness: 0, flow: 1, pressureSize: true, minSize: 0.02, pressureCurve: 1.4, taper: 40, taperOut: 60, stabilizer: 0.5, spacing: 0.05 }),
    P('Brush Pen', 'Ink', { engine: 'pixel', size: 16, softness: 0.05, flow: 1, pressureSize: true, minSize: 0.05, taper: 60, taperOut: 90, speedSize: 0.4, stabilizer: 0.45, spacing: 0.05 }),
    P('Calligraphy', 'Ink', { engine: 'pixel', size: 26, softness: 0.1, flow: 1, roundness: 0.3, angle: 45, pressureSize: false, stabilizer: 0.3 }),
    P('Italic Nib', 'Ink', { engine: 'nib', size: 24, flow: 1, angle: 40, roundness: 0.9, pressureSize: true, minSize: 0.5, stabilizer: 0.4 }),
    P('Marker', 'Ink', { engine: 'pixel', size: 18, softness: 0.15, flow: 0.35, opacity: 1, pressureSize: false, roundness: 0.85 }),
    P('Felt Tip', 'Ink', { engine: 'pixel', size: 14, softness: 0.2, flow: 1, opacity: 0.7, pressureSize: false, blend: 'multiply', spacing: 0.06 }),
    P('Highlighter', 'Ink', { engine: 'pixel', size: 26, softness: 0.05, flow: 1, opacity: 0.45, roundness: 0.35, angle: 90, tip: 'square', pressureSize: false, blend: 'multiply', stabilizer: 0.6 }),
    P('Technical Pen', 'Ink', { engine: 'pixel', size: 3, softness: 0, flow: 1, pressureSize: false, stabilizer: 0.65, spacing: 0.05 }),
    /* Paint */
    P('Hard Round', 'Paint', { engine: 'pixel', size: 20, softness: 0.05, flow: 1, pressureSize: true }),
    P('Soft Brush', 'Paint', { engine: 'pixel', size: 60, softness: 0.9, flow: 0.5, pressureOpacity: true, pressureSize: true }),
    P('Oil Bristle', 'Paint', { engine: 'bristle', size: 34, flow: 0.9, bristles: 28, bleed: 0.4, splay: 0.5, load: 900, pressureSize: true, pressureOpacity: false, stabilizer: 0.25 }),
    P('Dry Bristle', 'Paint', { engine: 'bristle', size: 42, flow: 0.75, bristles: 18, load: 260, bleed: 0.2, splay: 0.7, pressureSize: true, stabilizer: 0.2 }),
    P('Fan Brush', 'Paint', { engine: 'pixel', size: 46, softness: 0.25, flow: 0.5, roundness: 0.18, angle: 0, spacing: 0.2, pressureOpacity: true }),
    P('Flat Brush', 'Paint', { engine: 'pixel', size: 36, tip: 'flat', flow: 0.6, spacing: 0.06, angleMode: 'direction', angle: 90, pressureOpacity: true }),
    P('Gouache', 'Paint', { engine: 'pixel', size: 32, tip: 'gouache', flow: 0.55, spacing: 0.1, angleMode: 'random', texture: 'canvas', textureStrength: 0.25, pressureOpacity: true }),
    P('Acrylic Mixer', 'Paint', { engine: 'mixer', size: 30, tip: 'gouache', angleMode: 'random', softness: 0.25, flow: 0.85, bleed: 0.45, load: 1600, spacing: 0.06, texture: 'canvas', textureStrength: 0.25, pressureSize: true, taperOut: 40 }),
    P('Wet Blender', 'Paint', { engine: 'smudge', size: 44, softness: 1, flow: 0.35, pressureSize: true, spacing: 0.1 }),
    P('Impasto Knife', 'Paint', { engine: 'mixer', size: 40, tip: 'square', roundness: 0.35, angleMode: 'direction', flow: 0.95, bleed: 0.35, spacing: 0.05, pressureSize: false }),
    P('Tapered Liner', 'Ink', { engine: 'pixel', size: 8, softness: 0, flow: 1, pressureSize: true, minSize: 0.02, taper: 50, taperOut: 80, stabilizer: 0.55, spacing: 0.04, pressurePts: [[0.1, 0.45], [0.35, 0.95]] }),
    P('Dry Ink', 'Ink', { engine: 'pixel', size: 18, softness: 0.05, flow: 1, dualTip: 'chalk', dualSize: 0.45, dualCount: 4, taperOut: 60, pressureSize: true, spacing: 0.05 }),
    /* Watercolour */
    P('Watercolour Wash', 'Watercolour', { engine: 'watercolor', size: 70, tip: 'watercolour', flow: 0.12, opacity: 0.9, spacing: 0.07, angleMode: 'random', texture: 'watercolour', textureStrength: 0.35, wetEdges: 0.7, bleed: 0.4, blend: 'multiply', pressureSize: true, minSize: 0.5, stabilizer: 0.2 }),
    P('Watercolour Round', 'Watercolour', { engine: 'watercolor', size: 34, tip: 'watercolour', flow: 0.2, spacing: 0.06, angleMode: 'random', texture: 'watercolour', textureStrength: 0.3, wetEdges: 0.6, bleed: 0.3, blend: 'multiply', pressureSize: true, minSize: 0.3 }),
    P('Watercolour Detail', 'Watercolour', { engine: 'watercolor', size: 12, tip: 'watercolour', flow: 0.35, spacing: 0.05, angleMode: 'random', texture: 'watercolour', textureStrength: 0.25, wetEdges: 0.5, bleed: 0.2, blend: 'multiply', pressureSize: true, minSize: 0.2 }),
    P('Granulating Wash', 'Watercolour', { engine: 'watercolor', size: 80, tip: 'cloud', flow: 0.14, spacing: 0.07, angleMode: 'random', texture: 'rough', textureStrength: 0.65, wetEdges: 0.4, bleed: 0.5, blend: 'multiply', pressureSize: true, minSize: 0.6 }),
    P('Wet Bloom', 'Watercolour', { engine: 'watercolor', size: 60, tip: 'watercolour', flow: 0.1, spacing: 0.25, scatter: 0.6, sizeJitter: 0.4, angleMode: 'random', texture: 'watercolour', textureStrength: 0.3, wetEdges: 0.9, bleed: 0.6, blend: 'multiply', hueJitter: 0.03 }),
    P('Ink Wash', 'Watercolour', { engine: 'watercolor', size: 50, tip: 'watercolour', flow: 0.12, spacing: 0.06, angleMode: 'random', texture: 'watercolour', textureStrength: 0.2, wetEdges: 0.5, blend: 'multiply', pressureOpacity: true }),
    P('Palette Knife', 'Paint', { engine: 'mixer', size: 46, tip: 'square', roundness: 0.25, angleMode: 'direction', flow: 1, bleed: 0.6, load: 700, spacing: 0.04, pressureSize: false }),
    P('Scumble', 'Paint', { engine: 'pixel', size: 50, tip: 'bristle', flow: 0.45, angleMode: 'random', dualTip: 'sponge', dualSize: 0.6, dualCount: 3, texture: 'canvas', textureStrength: 0.5, spacing: 0.1, pressureOpacity: true }),
    /* Dry media */
    P('Crayon', 'Dry Media', { engine: 'pixel', size: 16, tip: 'chalk', flow: 0.95, spacing: 0.06, angleMode: 'random', texture: 'crayon', textureStrength: 0.85, pressureSize: true, minSize: 0.7, pressureOpacity: false }),
    P('Wax Crayon (thick)', 'Dry Media', { engine: 'pixel', size: 28, tip: 'chalk', flow: 1, spacing: 0.05, angleMode: 'random', texture: 'crayon', textureStrength: 0.9, pressureSize: false, opacityJitter: 0.1 }),
    P('Oil Pastel', 'Dry Media', { engine: 'mixer', size: 26, tip: 'chalk', flow: 0.95, bleed: 0.25, spacing: 0.06, angleMode: 'random', texture: 'rough', textureStrength: 0.6, pressureSize: true, minSize: 0.6 }),
    P('Soft Pastel', 'Dry Media', { engine: 'pixel', size: 40, tip: 'chalk', flow: 0.45, spacing: 0.08, angleMode: 'random', texture: 'rough', textureStrength: 0.75, pressureOpacity: true }),
    P('Chalk', 'Dry Media', { engine: 'pixel', size: 34, softness: 0.85, flow: 0.25, scatter: 0.25, pressureOpacity: true, spacing: 0.18 }),
    P('Board Chalk', 'Dry Media', { engine: 'pixel', size: 22, tip: 'chalk', flow: 0.9, spacing: 0.07, angleMode: 'random', texture: 'sand', textureStrength: 0.7, pressureSize: false }),
    P('Charcoal', 'Dry Media', { engine: 'pixel', size: 30, softness: 0.7, flow: 0.35, scatter: 0.5, pressureOpacity: true }),
    P('Charcoal Stick', 'Dry Media', { engine: 'pixel', size: 26, tip: 'charcoal', flow: 0.7, spacing: 0.06, angleMode: 'direction', angle: 90, texture: 'charcoal', textureStrength: 0.7, pressureOpacity: true }),
    P('Conté', 'Dry Media', { engine: 'pixel', size: 14, tip: 'square', roundness: 0.5, angleMode: 'direction', flow: 0.8, spacing: 0.06, texture: 'paper', textureStrength: 0.65, pressureOpacity: true }),
    P('Grainy Charcoal', 'Dry Media', { engine: 'pixel', size: 34, tip: 'charcoal', flow: 0.8, dualTip: 'sponge', dualSize: 0.5, dualCount: 4, texture: 'charcoal', textureStrength: 0.6, angleMode: 'direction', spacing: 0.06, pressureOpacity: true, taperOut: 40 }),
    /* Airbrush & spray */
    P('Airbrush', 'Airbrush', { engine: 'airbrush', size: 80, softness: 1, flow: 0.06, pressureOpacity: true }),
    P('Fine Airbrush', 'Airbrush', { engine: 'airbrush', size: 24, softness: 1, flow: 0.08, pressureOpacity: true, stabilizer: 0.3 }),
    P('Spray', 'Airbrush', { engine: 'spray', size: 70, flow: 0.5, density: 30, scatter: 0 }),
    P('Spray Can', 'Airbrush', { engine: 'spray', size: 90, flow: 0.6, density: 70, particle: 0.6, pressureOpacity: true }),
    P('Splatter', 'Airbrush', { engine: 'spray', size: 90, flow: 0.4, density: 8, scatter: 0, pressureOpacity: true, particle: 3 }),
    P('Stipple', 'Airbrush', { engine: 'pixel', size: 6, softness: 0.3, flow: 0.8, spacing: 0.9, scatter: 0.9, pressureSize: true }),
    P('Spatter Tip', 'Airbrush', { engine: 'pixel', size: 60, tip: 'splatter', flow: 0.9, spacing: 0.9, angleMode: 'random', sizeJitter: 0.5, scatter: 0.4, pressureSize: false }),
    /* Texture */
    P('Sponge', 'Texture', { engine: 'pixel', size: 50, tip: 'sponge', flow: 0.5, spacing: 0.35, angleMode: 'random', sizeJitter: 0.2, pressureOpacity: true }),
    P('Cloud Brush', 'Texture', { engine: 'pixel', size: 90, tip: 'cloud', flow: 0.25, spacing: 0.2, angleMode: 'random', sizeJitter: 0.3, scatter: 0.3, pressureOpacity: true }),
    P('Smoke', 'Texture', { engine: 'pixel', size: 80, tip: 'smoke', flow: 0.2, spacing: 0.15, angleMode: 'direction', sizeJitter: 0.2, pressureOpacity: true }),
    P('Rake', 'Texture', { engine: 'pixel', size: 40, tip: 'rake', flow: 0.8, spacing: 0.04, angleMode: 'direction', angle: 90 }),
    P('Hair', 'Texture', { engine: 'pixel', size: 40, tip: 'hair', flow: 0.5, spacing: 0.1, angleMode: 'direction', pressureSize: true }),
    P('Dry Brush', 'Texture', { engine: 'pixel', size: 44, tip: 'dry', flow: 0.6, spacing: 0.05, angleMode: 'direction', angle: 90, pressureOpacity: true }),
    P('Canvas Texture', 'Texture', { engine: 'pixel', size: 60, softness: 0.6, flow: 0.5, texture: 'canvas', textureStrength: 0.8, pressureOpacity: true }),
    P('Concrete', 'Texture', { engine: 'pixel', size: 70, softness: 0.5, flow: 0.6, texture: 'concrete', textureStrength: 0.8 }),
    P('Wood Grain', 'Texture', { engine: 'pixel', size: 70, softness: 0.4, flow: 0.6, texture: 'bark', textureStrength: 0.85 }),
    P('Halftone Shade', 'Texture', { engine: 'pixel', size: 60, softness: 0.7, flow: 0.7, texture: 'dots', textureStrength: 1, pressureOpacity: true }),
    /* Pattern fills (canvas-aligned repeating patterns through the brush) */
    P('Pattern: Bricks', 'Pattern', { engine: 'pixel', size: 60, softness: 0.1, flow: 1, fillPattern: 'Bricks', spacing: 0.1 }),
    P('Pattern: Red Bricks', 'Pattern', { engine: 'pixel', size: 70, softness: 0.1, flow: 1, fillPattern: 'Red Bricks', spacing: 0.1 }),
    P('Pattern: Stone Wall', 'Pattern', { engine: 'pixel', size: 70, softness: 0.1, flow: 1, fillPattern: 'Stone Wall', spacing: 0.1 }),
    P('Pattern: Screentone', 'Pattern', { engine: 'pixel', size: 60, softness: 0.05, flow: 1, fillPattern: 'Halftone', spacing: 0.1 }),
    P('Pattern: Hatching', 'Pattern', { engine: 'pixel', size: 60, softness: 0.3, flow: 1, fillPattern: 'Hatching (fine)', spacing: 0.1 }),
    P('Pattern: Scales', 'Pattern', { engine: 'pixel', size: 60, softness: 0.1, flow: 1, fillPattern: 'Scales', spacing: 0.1 }),
    P('Pattern: Honeycomb', 'Pattern', { engine: 'pixel', size: 60, softness: 0.1, flow: 1, fillPattern: 'Honeycomb', spacing: 0.1 }),
    P('Pattern: Tartan', 'Pattern', { engine: 'pixel', size: 70, softness: 0.1, flow: 1, fillPattern: 'Tartan', spacing: 0.1 }),
    P('Pattern: Leopard', 'Pattern', { engine: 'pixel', size: 70, softness: 0.2, flow: 1, fillPattern: 'Leopard', spacing: 0.1 }),
    P('Pattern: Grass', 'Pattern', { engine: 'pixel', size: 70, softness: 0.3, flow: 1, fillPattern: 'Grass Texture', spacing: 0.1 }),
    P('Pattern: Water', 'Pattern', { engine: 'pixel', size: 70, softness: 0.3, flow: 1, fillPattern: 'Water', spacing: 0.1 }),
    /* Scatter (sprite) brushes */
    P('Pattern Brush', 'Scatter', { engine: 'pixel', pattern: 'Leaves', size: 60, spacing: 0.4, scatter: 0.25, flow: 0.95, pressureSize: true, stabilizer: 0.1 }),
    P('Autumn Leaves', 'Scatter', { engine: 'pixel', pattern: 'Autumn Leaves', size: 60, spacing: 0.45, scatter: 0.3, flow: 1, pressureSize: true }),
    P('Grass Scatter', 'Scatter', { engine: 'pixel', pattern: 'Grass', size: 60, spacing: 0.3, scatter: 0.15, flow: 1, pressureSize: true }),
    P('Bushes', 'Scatter', { engine: 'pixel', pattern: 'Bushes', size: 70, spacing: 0.35, scatter: 0.2, flow: 1 }),
    P('Flower Field', 'Scatter', { engine: 'pixel', pattern: 'Flowers', size: 50, spacing: 0.5, scatter: 0.4, flow: 1 }),
    P('Sakura', 'Scatter', { engine: 'pixel', pattern: 'Sakura Petals', size: 50, spacing: 0.6, scatter: 0.8, flow: 1, sizeJitter: 0.3 }),
    P('Stars', 'Scatter', { engine: 'pixel', pattern: 'Stars', size: 40, spacing: 0.7, scatter: 0.8, flow: 1, sizeJitter: 0.4 }),
    P('Sparkles', 'Scatter', { engine: 'pixel', pattern: 'Sparkles', size: 50, spacing: 0.8, scatter: 0.8, flow: 1, sizeJitter: 0.5 }),
    P('Confetti', 'Scatter', { engine: 'pixel', pattern: 'Confetti', size: 50, spacing: 0.5, scatter: 0.8, flow: 1 }),
    P('Bubbles', 'Scatter', { engine: 'pixel', pattern: 'Bubbles', size: 60, spacing: 0.6, scatter: 0.6, flow: 1, sizeJitter: 0.4 }),
    P('Snowfall', 'Scatter', { engine: 'pixel', pattern: 'Snow', size: 60, spacing: 0.5, scatter: 1, flow: 1 }),
    P('Clouds', 'Scatter', { engine: 'pixel', pattern: 'Clouds', size: 120, spacing: 0.35, scatter: 0.3, flow: 1, sizeJitter: 0.3 }),
    P('Rubble', 'Scatter', { engine: 'pixel', pattern: 'Rubble', size: 60, spacing: 0.45, scatter: 0.4, flow: 1 }),
    P('Pebbles', 'Scatter', { engine: 'pixel', pattern: 'Pebbles', size: 50, spacing: 0.5, scatter: 0.4, flow: 1 }),
    P('Fur', 'Scatter', { engine: 'pixel', pattern: 'Fur', size: 40, spacing: 0.15, scatter: 0.1, flow: 1, patternRandom: 0.3 }),
    P('Hearts', 'Scatter', { engine: 'pixel', pattern: 'Hearts', size: 40, spacing: 0.7, scatter: 0.7, flow: 1, sizeJitter: 0.4 }),
    P('Splatter Drops', 'Scatter', { engine: 'pixel', pattern: 'Splatter Drops', size: 70, spacing: 0.8, scatter: 0.6, flow: 1, sizeJitter: 0.5 }),
    P('Embers', 'Scatter', { engine: 'pixel', pattern: 'Embers', size: 50, spacing: 0.6, scatter: 0.8, flow: 1, blend: 'screen' }),
    /* FX */
    P('Neon Glow', 'FX', { engine: 'glow', size: 40, flow: 0.35, spacing: 0.08, blend: 'screen', pressureSize: true, stabilizer: 0.4 }),
    P('Light Saber', 'FX', { engine: 'glow', size: 24, flow: 0.6, spacing: 0.05, blend: 'add', pressureSize: false, stabilizer: 0.6 }),
    P('Rainbow', 'FX', { engine: 'pixel', size: 26, softness: 0.3, flow: 0.9, spacing: 0.06, hueJitter: 1, pressureSize: true }),
    P('Pixel Art', 'FX', { engine: 'pixelart', size: 1, flow: 1, stabilizer: 0, pressureSize: false, pixelPerfect: true }),
    P('Pixel Block', 'FX', { engine: 'pixelart', size: 4, flow: 1, stabilizer: 0, pressureSize: false }),
    P('Shadow Multiply', 'FX', { engine: 'pixel', size: 60, softness: 0.8, flow: 0.25, blend: 'multiply', pressureOpacity: true }),
    P('Light Overlay', 'FX', { engine: 'pixel', size: 70, softness: 0.9, flow: 0.25, blend: 'overlay', pressureOpacity: true }),
    /* Retouch */
    P('Smudge', 'Retouch', { engine: 'smudge', size: 30, softness: 0.6, flow: 0.6, pressureSize: true }),
    P('Blur Brush', 'Retouch', { engine: 'blur', size: 40, softness: 0.7, flow: 0.6, spacing: 0.15 }),
    P('Clone Stamp', 'Retouch', { engine: 'clone', size: 34, softness: 0.5, flow: 1, pressureSize: true, spacing: 0.1 }),
    P('Dodge (Lighten)', 'Retouch', { engine: 'dodge', size: 40, softness: 0.8, flow: 0.5, pressureOpacity: true }),
    P('Burn (Darken)', 'Retouch', { engine: 'burn', size: 40, softness: 0.8, flow: 0.5, pressureOpacity: true }),
    /* Erase */
    P('Eraser Soft', 'Erase', { engine: 'eraser', size: 40, softness: 0.8, flow: 0.7 }),
    P('Eraser Hard', 'Erase', { engine: 'eraser', size: 20, softness: 0, flow: 1 }),
    P('Eraser Textured', 'Erase', { engine: 'eraser', size: 40, tip: 'chalk', flow: 0.8, spacing: 0.08, angleMode: 'random', texture: 'rough', textureStrength: 0.6 }),
    P('Pixel Eraser', 'Erase', { engine: 'pixelart', erase: true, size: 4, flow: 1, stabilizer: 0, pressureSize: false }),
  ];

  const CATS = ['Sketch', 'Ink', 'Paint', 'Watercolour', 'Dry Media', 'Airbrush', 'Texture', 'Pattern', 'Scatter', 'FX', 'Retouch', 'Erase'];
  ND.Presets = { LIST, CATS };
})();
