/* Neon Draw — service worker (generated by tools/build-pwa.py — edit the template, not sw.js).
 * Caches the whole app so it opens and works offline once visited / installed. */
'use strict';
const VERSION = 'neondraw-2.5.2';
const FILES = [
  "./",
  "./css/app.css",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-48.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./js/adjust.js",
  "./js/ai-worker.js",
  "./js/ai.js",
  "./js/app.js",
  "./js/blend.js",
  "./js/document.js",
  "./js/effects.js",
  "./js/engine.js",
  "./js/files.js",
  "./js/filters.js",
  "./js/harmony.js",
  "./js/heal.js",
  "./js/icons.js",
  "./js/main.js",
  "./js/paper.js",
  "./js/patterns.js",
  "./js/patterns2.js",
  "./js/presets.js",
  "./js/psd.js",
  "./js/refine.js",
  "./js/render.js",
  "./js/selection.js",
  "./js/smartsel.js",
  "./js/stamps.js",
  "./js/storage.js",
  "./js/textures.js",
  "./js/tips.js",
  "./js/tools2.js",
  "./js/ui/adjustpanel.js",
  "./js/ui/aipanel.js",
  "./js/ui/brushes.js",
  "./js/ui/colour.js",
  "./js/ui/command.js",
  "./js/ui/controls.js",
  "./js/ui/dialogs.js",
  "./js/ui/layers.js",
  "./js/ui/menus.js",
  "./js/ui/popup.js",
  "./js/ui/selectmask.js",
  "./js/ui/toolbar.js",
  "./js/util.js",
  "./js/viewport.js",
  "./manifest.webmanifest"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES)));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('neondraw-') && k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The page asks the new version to take over when the user clicks "Update".
self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : Response.error()))),
  );
});
